"""FastAPI application for the Mexican Penal Code RAG service.

Endpoints
---------
POST /v1/query              Full blocking RAG pipeline → QueryResponse
POST /v1/query/stream       Streaming SSE variant (tokens as they arrive)
GET  /v1/health             Live connectivity probe (Pinecone + Anthropic)
GET  /v1/metrics            Prometheus text exposition
POST /v1/evaluate           Admin-gated evaluation trigger (background task)
GET  /docs                  Swagger UI  (auto-generated by FastAPI)
GET  /redoc                 ReDoc UI    (auto-generated by FastAPI)

Environment variables
---------------------
PINECONE_API_KEY      required
PINECONE_INDEX_NAME   required
ANTHROPIC_API_KEY     required
ADMIN_API_KEY         required for POST /v1/evaluate
ALLOWED_ORIGINS       comma-separated list of CORS origins  (default: "*")
RATE_LIMIT_REQUESTS   requests allowed per window           (default: 20)
RATE_LIMIT_WINDOW_S   rate-limit window in seconds          (default: 60)
"""

from __future__ import annotations

import asyncio
import json
import logging
import time
import uuid
from contextlib import asynccontextmanager

from fastapi import (
    APIRouter,
    BackgroundTasks,
    Depends,
    FastAPI,
    Header,
    HTTPException,
    Query,
    Request,
)
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from prometheus_client import (
    CONTENT_TYPE_LATEST,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
)
from sse_starlette.sse import EventSourceResponse
from starlette.exceptions import HTTPException as StarletteHTTPException

import src.retrieval.pipeline as _pipeline
from src.api.config import settings
from src.api.metrics_collector import MetricsCollector
from src.api.middleware import (
    RateLimiter,
    RequestIDMiddleware,
    configure_logging,
    generic_exception_handler,
    http_exception_handler,
    validation_exception_handler,
)
from src.api.models import (
    ErrorResponse,
    EvalRequest,
    HealthResponse,
    QueryRequest,
    QueryResponse,
    RetrievalMetadata,
    split_citations,
)
from src.api.request_logger import RequestLogger
from src.retrieval.generator import (
    ACTIVE_MODEL,
    ACTIVE_PROMPT_VERSION,
    build_citations,
    extract_article_numbers,
)

configure_logging(level=settings.log_level_int)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Prometheus metrics
# ---------------------------------------------------------------------------

QUERY_COUNTER = Counter(
    "legal_query_total",
    "Total RAG query requests",
    ["status"],  # "success" | "error" | "rate_limited"
)
QUERY_LATENCY = Histogram(
    "legal_query_duration_seconds",
    "End-to-end query wall time",
    ["endpoint"],  # "query" | "stream"
    buckets=[1, 5, 10, 15, 20, 30, 60],
)
RETRIEVAL_LATENCY = Histogram(
    "legal_retrieval_duration_seconds",
    "Retrieval stage wall time (expand → search → rerank)",
    buckets=[1, 3, 5, 8, 10, 15, 20],
)
GENERATION_LATENCY = Histogram(
    "legal_generation_duration_seconds",
    "Generation stage wall time (Claude Haiku call)",
    buckets=[0.5, 1, 2, 3, 5, 10],
)
HALLUCINATION_COUNTER = Counter(
    "legal_hallucination_flags_total",
    "Article citations absent from retrieved context",
)
ACTIVE_REQUESTS = Gauge(
    "legal_active_requests",
    "Requests currently being processed",
)


# ---------------------------------------------------------------------------
# Configuration constants (resolved once at import time)
# ---------------------------------------------------------------------------

_RATE_LIMIT_REQUESTS: int = settings.rate_limit_requests
_RATE_LIMIT_WINDOW_S: float = float(settings.rate_limit_window_s)
_ADMIN_API_KEY: str = settings.admin_api_key


def _app_version() -> str:
    try:
        from importlib.metadata import version
        return version("legal-intelligence-engine")
    except Exception:
        return "0.1.0"


_VERSION = _app_version()


_rate_limiter = RateLimiter(
    max_requests=_RATE_LIMIT_REQUESTS,
    window_seconds=int(_RATE_LIMIT_WINDOW_S),
)
_metrics = MetricsCollector()
_request_logger: RequestLogger | None = None  # initialised in lifespan


# ---------------------------------------------------------------------------
# FastAPI dependencies
# ---------------------------------------------------------------------------


async def _check_rate_limit(request: Request) -> None:
    """Dependency: raise 429 if the client IP has exceeded the rate limit."""
    ip = request.client.host if request.client else "unknown"
    if not _rate_limiter.is_allowed(ip):
        QUERY_COUNTER.labels(status="rate_limited").inc()
        retry_after = int(_rate_limiter.time_until_next(ip)) + 1
        raise HTTPException(
            status_code=429,
            detail=ErrorResponse(
                error="Rate limit exceeded",
                detail=f"Retry after {retry_after}s ({_RATE_LIMIT_REQUESTS} req/{int(_RATE_LIMIT_WINDOW_S)}s per IP)",
                request_id=getattr(request.state, "request_id", "unknown"),
            ).model_dump(),
            headers={"Retry-After": str(retry_after)},
        )


async def _verify_admin_key(
    x_admin_key: str = Header(..., alias="X-Admin-Key"),
) -> None:
    """Dependency: validate the X-Admin-Key header for admin-only endpoints."""
    if not _ADMIN_API_KEY:
        raise HTTPException(
            status_code=503,
            detail="Admin access is not configured on this instance (ADMIN_API_KEY not set)",
        )
    if x_admin_key != _ADMIN_API_KEY:
        raise HTTPException(status_code=403, detail="Invalid admin key")


# ---------------------------------------------------------------------------
# Lifespan — startup probes and shutdown cleanup
# ---------------------------------------------------------------------------


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Probe external services on startup; log clean shutdown."""
    global _request_logger

    app.state.start_time = time.monotonic()
    _request_logger = RequestLogger()

    logger.info("Starting Legal Intelligence Engine v%s", _VERSION)

    # ── Pinecone probe ──────────────────────────────────────────────────────
    vector_count = 0
    try:
        from pinecone import Pinecone

        _pc = Pinecone(api_key=settings.pinecone_api_key)
        _idx = _pc.Index(settings.pinecone_index_name)
        _stats = await asyncio.to_thread(_idx.describe_index_stats)
        vector_count = _stats.total_vector_count
        logger.info(
            "Pinecone connected",
            extra={"index": settings.pinecone_index_name, "vectors": vector_count},
        )
    except Exception as exc:
        logger.warning("Pinecone probe failed: %s", exc)

    # ── Anthropic probe (key presence only; avoids API cost at startup) ─────
    anthropic_ok = bool(settings.anthropic_api_key)
    if anthropic_ok:
        logger.info("Anthropic API key present")
    else:
        logger.warning("ANTHROPIC_API_KEY not set — generation will fail at query time")

    yield  # ── application is running ──────────────────────────────────────

    if _request_logger is not None:
        _request_logger.close()
    logger.info("Legal Intelligence Engine shutting down")


# ---------------------------------------------------------------------------
# Application and router
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Legal Intelligence Engine",
    description=(
        "Production RAG system for the **Mexican Penal Code (CDMX)**.\n\n"
        "Implements a 3-stage retrieval pipeline:\n"
        "1. **Query expansion** — Claude Haiku generates 3 alternative phrasings\n"
        "2. **Dense vector search** — Pinecone top-20 per variant, deduplicated\n"
        "3. **Cross-encoder reranking** — MiniLM-L6 reranks to top-k\n\n"
        "Followed by answer **generation** via Claude Haiku with structured "
        "citation extraction and hallucination detection."
    ),
    version=_VERSION,
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
)

# CORS — permissive by default; lock down via ALLOWED_ORIGINS in production
_allowed_origins = settings.allowed_origins_list
app.add_middleware(
    CORSMiddleware,
    allow_origins=_allowed_origins,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
    expose_headers=["X-Request-ID", "Retry-After"],
)
app.add_middleware(RequestIDMiddleware)

router = APIRouter(prefix="/v1")


# ---------------------------------------------------------------------------
# Exception handlers — uniform ErrorResponse envelope for all 4xx/5xx
# Handlers are defined in src/api/middleware.py; registered here.
# ---------------------------------------------------------------------------

app.exception_handler(RequestValidationError)(validation_exception_handler)
app.exception_handler(HTTPException)(http_exception_handler)
app.exception_handler(StarletteHTTPException)(http_exception_handler)  # covers unmatched-route 404s
app.exception_handler(Exception)(generic_exception_handler)


# ---------------------------------------------------------------------------
# GET /v1/health
# ---------------------------------------------------------------------------


@router.get(
    "/health",
    response_model=HealthResponse,
    tags=["ops"],
    summary="Service health probe",
)
async def health(request: Request) -> HealthResponse:
    """Live connectivity and readiness probe.

    Performs a real ``describe_index_stats`` call against the configured
    Pinecone index (not just a ping) and checks whether ``ANTHROPIC_API_KEY``
    is present in the environment.  The overall ``status`` field summarises
    both checks:

    | status | meaning |
    |--------|---------|
    | `healthy` | Pinecone reachable **and** Anthropic key present |
    | `degraded` | Exactly one of the two checks passed |
    | `unhealthy` | Both checks failed |

    Also returns ``index_vector_count`` (useful for confirming the ingestion
    pipeline has run) and ``uptime_seconds`` since process start.

    This endpoint is **not rate-limited** and adds no auth requirement so it
    can be polled freely by load-balancer health checks and uptime monitors.
    """
    pinecone_ok = False
    vector_count = 0
    try:
        from pinecone import Pinecone

        _pc = Pinecone(api_key=settings.pinecone_api_key)
        _idx = _pc.Index(settings.pinecone_index_name)
        _stats = await asyncio.to_thread(_idx.describe_index_stats)
        vector_count = _stats.total_vector_count
        pinecone_ok = True
    except Exception as exc:
        logger.warning("Health check: Pinecone probe failed: %s", exc)

    anthropic_ok = bool(settings.anthropic_api_key)

    if pinecone_ok and anthropic_ok:
        status = "healthy"
    elif pinecone_ok or anthropic_ok:
        status = "degraded"
    else:
        status = "unhealthy"

    uptime = time.monotonic() - getattr(request.app.state, "start_time", time.monotonic())

    return HealthResponse(
        status=status,
        pinecone_connected=pinecone_ok,
        anthropic_connected=anthropic_ok,
        index_vector_count=vector_count,
        uptime_seconds=round(uptime, 1),
        version=_VERSION,
    )


# ---------------------------------------------------------------------------
# GET /v1/metrics
# ---------------------------------------------------------------------------


@router.get(
    "/metrics",
    tags=["ops"],
    summary="Prometheus metrics",
    response_class=Response,
    responses={200: {"content": {"text/plain": {}}, "description": "Prometheus text format"}},
)
async def metrics() -> Response:
    """Prometheus metrics in text exposition format (`text/plain; version=0.0.4`).

    Scraped by Prometheus or any compatible collector.  All metric families
    use the ``legal_`` namespace.

    | Metric | Type | Description |
    |--------|------|-------------|
    | `legal_query_total` | counter | Requests by `status` label (`success`, `error`, `rate_limited`) |
    | `legal_query_duration_seconds` | histogram | End-to-end latency by `endpoint` (`query`, `stream`) |
    | `legal_retrieval_duration_seconds` | histogram | Retrieval stage wall time (expand → search → rerank) |
    | `legal_generation_duration_seconds` | histogram | Generation stage wall time (Claude API call) |
    | `legal_hallucination_flags_total` | counter | Article citations absent from retrieved context |
    | `legal_active_requests` | gauge | Requests currently being processed |
    """
    return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)


# ---------------------------------------------------------------------------
# POST /v1/query
# ---------------------------------------------------------------------------


@router.post(
    "/query",
    response_model=QueryResponse,
    responses={
        422: {"model": ErrorResponse, "description": "Validation error"},
        429: {"model": ErrorResponse, "description": "Rate limit exceeded"},
        500: {"model": ErrorResponse, "description": "Pipeline error"},
    },
    tags=["rag"],
    summary="RAG query (blocking)",
)
async def query_endpoint(
    req: QueryRequest,
    request: Request,
    _: None = Depends(_check_rate_limit),
) -> QueryResponse:
    """Run the full RAG pipeline and return a structured answer.

    Executes four stages synchronously (offloaded to a thread pool so the
    event loop stays unblocked):

    1. **Query expansion** — Claude Haiku generates 3 alternative phrasings of
       the question to improve recall.
    2. **Dense search** — Pinecone returns up to `top_k × 4` candidate chunks
       per variant; results are merged and deduplicated by chunk ID.
    3. **Cross-encoder reranking** — MiniLM-L6 reranks candidates to `top_k`
       highest-relevance chunks.
    4. **Generation** — Claude Haiku answers using the reranked chunks as
       context, then cited article numbers are extracted and cross-referenced
       against the retrieved chunks (hallucination detection).

    **Response** — `QueryResponse` containing the natural-language answer,
    grounded citations with cosine-similarity confidence scores, retrieval
    diagnostics (timing, expanded queries, chunk counts), and any article
    numbers cited by the model that were absent from retrieved context
    (`hallucination_flags`).

    **Errors**

    | Status | Condition |
    |--------|-----------|
    | 422 | Request body fails validation (question too short/long, top_k out of range) |
    | 429 | Client IP has exceeded the per-IP rate limit — check `Retry-After` header |
    | 500 | Pinecone or Anthropic API failure during the pipeline run |

    Set `stream: true` in the request body as a hint to switch to
    `POST /v1/query/stream` for token-by-token streaming.
    """
    request_id = getattr(request.state, "request_id", "unknown")
    ACTIVE_REQUESTS.inc()
    t0 = time.monotonic()

    try:
        result = await _pipeline.query(req.question, req.filters, req.top_k)
        total_ms = (time.monotonic() - t0) * 1000

        # Record Prometheus metrics
        QUERY_COUNTER.labels(status="success").inc()
        QUERY_LATENCY.labels(endpoint="query").observe(total_ms / 1000)
        RETRIEVAL_LATENCY.observe(result.retrieval.retrieval_time_ms / 1000)
        GENERATION_LATENCY.observe(result.generation_time_ms / 1000)
        n_flags = sum(1 for c in result.citations if c.hallucination_flag)
        if n_flags:
            HALLUCINATION_COUNTER.inc(n_flags)

        response = QueryResponse.from_generation_result(result, total_ms)  # type: ignore[arg-type]

        _metrics.record_request(total_ms, response.retrieval.avg_similarity_score)
        if _request_logger is not None:
            await asyncio.to_thread(
                _request_logger.log, request_id, req.question, response, 200
            )

        logger.info(
            "query complete",
            extra={
                "request_id": request_id,
                "total_ms": round(total_ms, 1),
                "retrieval_ms": result.retrieval.retrieval_time_ms,
                "generation_ms": result.generation_time_ms,
                "citations": len(response.citations),
                "hallucination_flags": len(response.hallucination_flags),
            },
        )
        return response

    except HTTPException:
        raise
    except Exception as exc:
        total_s = time.monotonic() - t0
        QUERY_COUNTER.labels(status="error").inc()
        QUERY_LATENCY.labels(endpoint="query").observe(total_s)
        _metrics.record_error()
        logger.exception(
            "Query pipeline error",
            extra={"request_id": request_id},
        )
        raise HTTPException(
            status_code=500,
            detail=ErrorResponse(
                error="Pipeline error",
                detail=str(exc),
                request_id=request_id,
            ).model_dump(),
        ) from exc
    finally:
        ACTIVE_REQUESTS.dec()


# ---------------------------------------------------------------------------
# POST /v1/query/stream
# ---------------------------------------------------------------------------


@router.post(
    "/query/stream",
    tags=["rag"],
    summary="RAG query (SSE streaming)",
    responses={
        429: {"model": ErrorResponse, "description": "Rate limit exceeded"},
        500: {"description": "Error event sent in stream"},
    },
    response_class=EventSourceResponse,
)
async def query_stream_endpoint(
    req: QueryRequest,
    request: Request,
    _: None = Depends(_check_rate_limit),
) -> EventSourceResponse:
    """Stream the full RAG pipeline as a sequence of Server-Sent Events.

    The stream delivers **three event types** in order:

    ``event: retrieval``
        Emitted once, immediately after the retrieval stage completes
        (expand → search → rerank).  Data is a JSON-serialised
        ``RetrievalMetadata`` object.  Clients can display chunk count,
        expanded queries, and latency before the first token arrives.

    ``event: token``
        Emitted for every text token from Claude Haiku.  Data is
        ``{"token": "<text>"}`` so clients can incrementally render the
        answer as it streams.

    ``event: complete``
        Emitted once after the last token.  Data is a JSON-serialised
        ``QueryResponse`` — identical to the response from ``POST /v1/query``
        including grounded citations and hallucination flags.  Citations are
        extracted post-hoc from the accumulated answer text; no second LLM
        call is made.

    ``event: error``
        Emitted if an unhandled exception occurs at any stage.  Data is
        ``{"error": "<message>", "request_id": "<id>"}``.  The connection is
        then closed.

    **SSE client example** (JavaScript)::

        const source = new EventSource(...)  // not supported for POST — use fetch + ReadableStream
        // or with fetch:
        const resp = await fetch('/v1/query/stream', {method:'POST', body: JSON.stringify(req)})
        const reader = resp.body.getReader()
    """
    request_id = getattr(request.state, "request_id", "unknown")
    t0 = time.monotonic()
    ACTIVE_REQUESTS.inc()

    async def _event_generator():
        try:
            # ── Event 1: retrieval ──────────────────────────────────────────
            # Run retrieval in its own step so we can emit metadata before
            # the (slow) generation stage starts.
            retrieval = await _pipeline.retrieve(req.question, req.filters, req.top_k)
            retrieval_meta = RetrievalMetadata.from_retrieval_result(retrieval)
            yield {
                "event": "retrieval",
                "data": retrieval_meta.model_dump_json(),
            }

            # ── Event 2: token (one per Claude output token) ────────────────
            # Pass the pre-computed RetrievalResult to skip a second retrieval
            # call inside query_stream().
            gen_t0 = time.monotonic()
            full_text_parts: list[str] = []

            async for token in _pipeline.query_stream(
                req.question, req.filters, retrieval=retrieval
            ):
                full_text_parts.append(token)
                yield {
                    "event": "token",
                    "data": json.dumps({"token": token}),
                }

            gen_ms = (time.monotonic() - gen_t0) * 1000
            full_text = "".join(full_text_parts)

            # ── Post-stream citation extraction (no second LLM call) ────────
            # Reuse the same regex + chunk cross-reference logic the blocking
            # endpoint uses, but applied to the accumulated streamed text.
            article_numbers = extract_article_numbers(full_text)
            citations = build_citations(article_numbers, retrieval.chunks)
            grounded, flagged = split_citations(citations)

            total_ms = (time.monotonic() - t0) * 1000

            # ── Event 3: complete ───────────────────────────────────────────
            complete = QueryResponse(
                answer=full_text,
                citations=grounded,
                retrieval=retrieval_meta,
                generation_time_ms=round(gen_ms, 2),
                total_time_ms=round(total_ms, 2),
                model=ACTIVE_MODEL,
                prompt_version=ACTIVE_PROMPT_VERSION,
                hallucination_flags=flagged,
            )
            yield {
                "event": "complete",
                "data": complete.model_dump_json(),
            }

            _metrics.record_request(total_ms, retrieval_meta.avg_similarity_score)
            if _request_logger is not None:
                await asyncio.to_thread(
                    _request_logger.log, request_id, req.question, complete, 200
                )

            # ── Prometheus ──────────────────────────────────────────────────
            QUERY_COUNTER.labels(status="success").inc()
            QUERY_LATENCY.labels(endpoint="stream").observe(total_ms / 1000)
            RETRIEVAL_LATENCY.observe(retrieval.retrieval_time_ms / 1000)
            GENERATION_LATENCY.observe(gen_ms / 1000)
            if flagged:
                HALLUCINATION_COUNTER.inc(len(flagged))

            logger.info(
                "stream complete",
                extra={
                    "request_id": request_id,
                    "total_ms": round(total_ms, 1),
                    "retrieval_ms": retrieval.retrieval_time_ms,
                    "generation_ms": round(gen_ms, 1),
                    "tokens": len(full_text_parts),
                    "citations": len(grounded),
                    "hallucination_flags": len(flagged),
                },
            )

        except Exception as exc:
            QUERY_COUNTER.labels(status="error").inc()
            _metrics.record_error()
            logger.exception(
                "Streaming pipeline error",
                extra={"request_id": request_id},
            )
            yield {
                "event": "error",
                "data": json.dumps({"error": str(exc), "request_id": request_id}),
            }
        finally:
            ACTIVE_REQUESTS.dec()

    return EventSourceResponse(_event_generator())


# ---------------------------------------------------------------------------
# POST /v1/evaluate  (admin-gated, async background task)
# ---------------------------------------------------------------------------


def _run_evaluation_bg(req: EvalRequest, job_id: str) -> None:
    """Background task that runs the full RAGAS + citation evaluation.

    Executed in a thread-pool worker so it does not block the event loop.
    Results are saved to ``results/eval_{run_id}.json``.

    Args:
        req:    The EvalRequest from the API caller.
        job_id: Short hex ID to correlate background log lines.
    """
    from src.evaluation.evaluator import Evaluator  # lazy import — heavy deps

    try:
        logger.info(
            "Eval job started",
            extra={"job_id": job_id, "test_set": req.test_set_path},
        )
        evaluator = Evaluator(test_set_path=req.test_set_path)

        run = evaluator.run(
            categories=[req.category] if req.category else None,
        )

        # If a single question_id was requested, filter post-run
        if req.question_id:
            run.results = [r for r in run.results if r.question_id == req.question_id]
            run.recalculate_aggregates()

        out_path = f"results/eval_{run.run_id}.json"
        run.save(out_path)

        summary = run.score_summary()
        logger.info(
            "Eval job complete",
            extra={"job_id": job_id, "run_id": run.run_id, "output": out_path, **summary},
        )

    except FileNotFoundError as exc:
        logger.error(
            "Eval job failed — test set not found",
            extra={"job_id": job_id, "error": str(exc)},
        )
    except Exception as exc:
        logger.exception(
            "Eval job failed",
            extra={"job_id": job_id, "error": str(exc)},
        )


@router.post(
    "/evaluate",
    status_code=202,
    tags=["ops"],
    summary="Trigger evaluation run (admin)",
    dependencies=[Depends(_verify_admin_key)],
    responses={
        202: {"description": "Evaluation job accepted and running in background"},
        403: {"model": ErrorResponse, "description": "Invalid admin key"},
        503: {"model": ErrorResponse, "description": "Admin access not configured"},
    },
)
async def evaluate(
    req: EvalRequest,
    background_tasks: BackgroundTasks,
    request: Request,
) -> dict:
    """Trigger a RAGAS + citation-accuracy evaluation run (admin only).

    Returns **202 Accepted** immediately; the full evaluation pipeline runs in
    a background thread pool worker and does **not** block the event loop or
    hold an HTTP connection open.

    **What runs in the background**:

    1. `Evaluator` loads the golden test set from `test_set_path`.
    2. For each question (optionally filtered by `category` or `question_id`),
       the full RAG pipeline is executed and scored with RAGAS metrics
       (faithfulness, answer relevance, context precision/recall) plus a custom
       citation-accuracy metric.
    3. Aggregate scores and per-question results are written to
       `results/eval_{run_id}.json`.

    **Tracking progress** — all log lines from the background job carry a
    `job_id` field matching the value returned in the 202 response.  Filter
    server logs by `job_id` to follow a specific run.

    **Auth** — the `X-Admin-Key` header must match the `ADMIN_API_KEY`
    environment variable.  Returns 403 on mismatch, 503 if `ADMIN_API_KEY`
    is not configured on this instance.

    | Status | Condition |
    |--------|-----------|
    | 202 | Job accepted and running in background |
    | 403 | `X-Admin-Key` header value does not match `ADMIN_API_KEY` |
    | 503 | `ADMIN_API_KEY` is not set on this instance |
    """
    job_id = uuid.uuid4().hex[:8]
    # BackgroundTasks runs in the thread pool after the response is sent.
    # Evaluator.run() calls asyncio.run() internally, which is safe inside
    # a thread-pool worker (separate event loop per thread).
    background_tasks.add_task(_run_evaluation_bg, req, job_id)

    return {
        "job_id": job_id,
        "status": "started",
        "message": (
            f"Evaluation job {job_id} is running in the background. "
            f"Results will be saved to results/eval_{{run_id}}.json. "
            f"Monitor progress via server logs (filter: job_id={job_id})."
        ),
        "request_id": getattr(request.state, "request_id", "unknown"),
    }


# ---------------------------------------------------------------------------
# GET /v1/requests  (monitoring — request log)
# ---------------------------------------------------------------------------


@router.get(
    "/requests",
    tags=["ops"],
    summary="Request log (monitoring)",
)
async def get_requests(
    limit: int = Query(500, ge=1, le=5000, description="Max rows to return"),
) -> list[dict]:
    """Return the most recent entries from the SQLite request log.

    Used by the Streamlit monitoring dashboard to avoid requiring direct
    filesystem access to the SQLite file.  Returns up to ``limit`` rows
    ordered newest-first.
    """
    if _request_logger is None:
        return []
    with _request_logger._lock:
        cursor = _request_logger.conn.execute(
            "SELECT * FROM requests ORDER BY timestamp DESC LIMIT ?", (limit,)
        )
        cols = [d[0] for d in cursor.description]
        return [dict(zip(cols, row, strict=False)) for row in cursor.fetchall()]


# ---------------------------------------------------------------------------
# GET /v1/eval-runs  (monitoring — evaluation results)
# ---------------------------------------------------------------------------


@router.get(
    "/eval-runs",
    tags=["ops"],
    summary="Evaluation run results (monitoring)",
)
async def get_eval_runs() -> list[dict]:
    """Return all evaluation run JSON files from the results/ directory.

    Used by the Streamlit monitoring dashboard so it does not need direct
    filesystem access to the results/ directory.  Results are returned sorted
    by timestamp ascending.
    """
    import json as _json
    from pathlib import Path as _Path

    runs: list[dict] = []
    base = _Path("results")
    if not base.exists():
        return runs
    for path in sorted(base.glob("*.json")):
        try:
            data = _json.loads(path.read_text(encoding="utf-8"))
            if "run_id" in data and "aggregate_scores" in data:
                data["_file"] = path.name
                runs.append(data)
        except Exception:
            pass
    return sorted(runs, key=lambda r: r.get("timestamp", ""))


# ---------------------------------------------------------------------------
# Mount the versioned router
# ---------------------------------------------------------------------------

app.include_router(router)
