"""Retrieval pipeline for the Mexican Penal Code RAG system.

Three-stage pipeline:
1. Query expansion  — Claude Haiku generates 3 alternative phrasings to improve
                      recall when the user's phrasing differs from legal text.
2. Hybrid search    — Dense vector search in Pinecone across all query variants,
                      with optional metadata filters; top_k=20 per variant;
                      results merged and deduplicated by chunk ID.
3. Reranking        — cross-encoder/ms-marco-MiniLM-L-6-v2 scores all candidates
                      and returns the top_k=5 most relevant chunks.

Environment variables (loaded from .env):
    PINECONE_API_KEY     — required
    PINECONE_INDEX_NAME  — required
    ANTHROPIC_API_KEY    — required
"""

import logging
import os
import time
from typing import Optional

import anthropic
from dotenv import load_dotenv
from pinecone import Pinecone
from pydantic import BaseModel
from sentence_transformers import CrossEncoder

from src.retrieval.prompts import EXPANSION_TEMPLATE

logger = logging.getLogger(__name__)

_CROSS_ENCODER_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"
_EMBED_MODEL = "llama-text-embed-v2"
_HAIKU_MODEL = "claude-haiku-4-5-20251001"


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


class RetrievedChunk(BaseModel):
    """A single chunk returned by the retrieval pipeline.

    Attributes:
        chunk_id:        Stable Pinecone vector ID (``{stem}-{index}``).
        text:            Raw text of the chunk.
        metadata:        All non-text metadata fields from Pinecone.
        similarity_score: Cosine similarity from the vector search stage.
        rerank_score:    Cross-encoder score (None before reranking).
    """

    chunk_id: str
    text: str
    metadata: dict
    similarity_score: float
    rerank_score: float | None = None


class RetrievalResult(BaseModel):
    """Output of a full retrieval pipeline run.

    Attributes:
        query:               The original user query.
        expanded_queries:    Alternative phrasings generated by Claude Haiku.
        candidates_retrieved: Total unique candidates before reranking.
        chunks:              Top-k reranked chunks (default k=5).
        retrieval_time_ms:   Wall-clock time for the entire pipeline in ms.
    """

    query: str
    expanded_queries: list[str]
    candidates_retrieved: int
    chunks: list[RetrievedChunk]
    retrieval_time_ms: float


# ---------------------------------------------------------------------------
# Retriever
# ---------------------------------------------------------------------------


class Retriever:
    """Three-stage retrieval pipeline: expand → search → rerank.

    Instantiation loads credentials from the environment and initialises
    the Pinecone client, Anthropic client, and cross-encoder model.
    The cross-encoder is loaded once and cached on the instance.

    Args:
        top_k_candidates: Number of results to fetch per query variant (Stage 2).
        top_k_final:      Number of reranked results to return (Stage 3).
        cross_encoder_model: HuggingFace model ID for the cross-encoder.
    """

    def __init__(
        self,
        top_k_candidates: int = 20,
        top_k_final: int = 5,
        cross_encoder_model: str = _CROSS_ENCODER_MODEL,
    ) -> None:
        load_dotenv()

        api_key = os.environ.get("PINECONE_API_KEY")
        index_name = os.environ.get("PINECONE_INDEX_NAME")
        anthropic_key = os.environ.get("ANTHROPIC_API_KEY")

        if not api_key:
            raise ValueError("PINECONE_API_KEY is not set.")
        if not index_name:
            raise ValueError("PINECONE_INDEX_NAME is not set.")
        if not anthropic_key:
            raise ValueError("ANTHROPIC_API_KEY is not set.")

        self._top_k_candidates = top_k_candidates
        self._top_k_final = top_k_final

        self._pc = Pinecone(api_key=api_key)
        self._index = self._pc.Index(index_name)
        self._anthropic = anthropic.Anthropic(api_key=anthropic_key)

        logger.info("Loading cross-encoder: %s", cross_encoder_model)
        self._cross_encoder = CrossEncoder(cross_encoder_model)

        logger.info(
            "Retriever initialised (top_k_candidates=%d, top_k_final=%d)",
            top_k_candidates,
            top_k_final,
        )

    # ------------------------------------------------------------------
    # Stage 1 — Query expansion
    # ------------------------------------------------------------------

    def _expand_query(self, query: str) -> list[str]:
        """Return [original] + up to 3 alternative phrasings via Claude Haiku.

        The original query is always first in the returned list so callers
        can separate it from the generated alternatives.
        """
        prompt = EXPANSION_TEMPLATE.format(question=query)
        response = self._anthropic.messages.create(
            model=_HAIKU_MODEL,
            max_tokens=256,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = response.content[0].text.strip()
        alternatives = [line.strip() for line in raw.splitlines() if line.strip()][:3]
        expanded = [query] + alternatives
        logger.debug("Query expanded into %d variants: %s", len(expanded), expanded)
        return expanded

    # ------------------------------------------------------------------
    # Stage 2 — Dense vector search
    # ------------------------------------------------------------------

    def _embed_query(self, query: str) -> list[float]:
        """Embed a single query string using input_type='query'."""
        response = self._pc.inference.embed(
            model=_EMBED_MODEL,
            inputs=[query],
            parameters={"input_type": "query", "truncate": "END"},
        )
        return response[0].values

    def _search_one(
        self,
        query: str,
        metadata_filter: Optional[dict],
    ) -> list[RetrievedChunk]:
        """Retrieve top_k_candidates chunks for a single query variant.

        Args:
            query:           A single query string (original or expanded).
            metadata_filter: Optional Pinecone filter dict.

        Returns:
            List of RetrievedChunk objects ordered by similarity score.
        """
        vector = self._embed_query(query)
        kwargs: dict = {
            "vector": vector,
            "top_k": self._top_k_candidates,
            "include_metadata": True,
        }
        if metadata_filter:
            kwargs["filter"] = metadata_filter

        response = self._index.query(**kwargs)

        chunks: list[RetrievedChunk] = []
        for match in response.matches:
            metadata = dict(match.metadata or {})
            text = metadata.pop("text", "")
            chunks.append(
                RetrievedChunk(
                    chunk_id=match.id,
                    text=text,
                    metadata=metadata,
                    similarity_score=float(match.score),
                )
            )
        return chunks

    def _hybrid_search(
        self,
        queries: list[str],
        metadata_filter: Optional[dict],
    ) -> list[RetrievedChunk]:
        """Search all query variants and return deduplicated candidates.

        For chunks retrieved by multiple query variants, only the entry with
        the highest similarity score is kept.

        Args:
            queries:         All query variants (original + expanded).
            metadata_filter: Optional Pinecone filter dict.

        Returns:
            Deduplicated list of RetrievedChunk, unsorted.
        """
        best: dict[str, RetrievedChunk] = {}
        for q in queries:
            for chunk in self._search_one(q, metadata_filter):
                existing = best.get(chunk.chunk_id)
                if existing is None or chunk.similarity_score > existing.similarity_score:
                    best[chunk.chunk_id] = chunk

        logger.debug(
            "Hybrid search: %d unique candidates from %d query variants",
            len(best),
            len(queries),
        )
        return list(best.values())

    # ------------------------------------------------------------------
    # Stage 3 — Cross-encoder reranking
    # ------------------------------------------------------------------

    def _rerank(
        self,
        query: str,
        candidates: list[RetrievedChunk],
        top_k: Optional[int] = None,
    ) -> list[RetrievedChunk]:
        """Score all candidates with the cross-encoder; return top_k chunks.

        Args:
            query:      The original user query (used as the reference text).
            candidates: All deduplicated candidates from Stage 2.
            top_k:      Override for the number of results to return.
                        Defaults to ``self._top_k_final`` when None.

        Returns:
            Top top_k chunks, sorted by rerank_score descending.
        """
        if not candidates:
            return []

        k = top_k if top_k is not None else self._top_k_final

        pairs = [(query, c.text) for c in candidates]
        scores: list[float] = self._cross_encoder.predict(pairs).tolist()

        for chunk, score in zip(candidates, scores):
            chunk.rerank_score = score

        ranked = sorted(candidates, key=lambda c: c.rerank_score, reverse=True)  # type: ignore[arg-type]
        top = ranked[:k]

        logger.debug(
            "Reranked %d candidates → top %d (best score: %.4f)",
            len(candidates),
            len(top),
            top[0].rerank_score if top else 0.0,
        )
        return top

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def retrieve(
        self,
        query: str,
        metadata_filter: Optional[dict] = None,
        top_k: Optional[int] = None,
    ) -> RetrievalResult:
        """Run the full three-stage retrieval pipeline.

        Example metadata filters::

            # Single chapter
            {"chapter": "Título Vigésimo Segundo"}

            # Article range
            {"article_number": {"$gte": "200", "$lte": "250"}}

        Args:
            query:           The user's natural-language legal question in Spanish.
            metadata_filter: Optional Pinecone filter to restrict the search scope.

        Returns:
            A RetrievalResult with the top-5 reranked chunks and timing metadata.
        """
        t0 = time.monotonic()

        # Stage 1 — expand query
        all_queries = self._expand_query(query)

        # Stage 2 — vector search across all variants, merge + deduplicate
        candidates = self._hybrid_search(all_queries, metadata_filter)

        # Stage 3 — cross-encoder reranking
        top_chunks = self._rerank(query, candidates, top_k=top_k)

        elapsed_ms = (time.monotonic() - t0) * 1000

        return RetrievalResult(
            query=query,
            expanded_queries=all_queries[1:],  # exclude the original
            candidates_retrieved=len(candidates),
            chunks=top_chunks,
            retrieval_time_ms=round(elapsed_ms, 2),
        )
